language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key: b44948b8-45e5-42c8-a0e8-9b5eca5129a3
  app: limitless-earth-36710
  on:
    repo: ericbelf/node-restaurants-app-mongoose
    branch: feature/with-tests
